# Generated by Django 5.2 on 2025-12-22 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('estado', models.CharField(choices=[('programada', 'Programada'), ('confirmada', 'Confirmada'), ('cancelada', 'Cancelada')], default='programada', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Atencion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('valor_consulta', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('valor_medicinas', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('especialidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='panel.especialidad')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='panel.servicio')),
            ],
        ),
    ]
