# Generated by Django 5.2 on 2025-12-23 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apoyodiagnostico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificacion', models.CharField(db_column='Identificacion', max_length=13)),
                ('tipodiagnostico', models.CharField(db_column='TipoDiagnostico', max_length=50)),
                ('nombreexamen', models.CharField(db_column='NombreExamen', max_length=50)),
                ('ruta', models.CharField(db_column='Ruta', max_length=200)),
                ('fechaexamen', models.DateTimeField(db_column='FechaExamen')),
                ('origen', models.CharField(db_column='Origen', max_length=50)),
            ],
            options={
                'db_table': 'ApoyoDiagnostico',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Atencionambulatoria',
            fields=[
                ('idatencionambulatoria', models.AutoField(db_column='idAtencionAmbulatoria', primary_key=True, serialize=False)),
                ('fechaatencion', models.DateTimeField(blank=True, db_column='fechaAtencion', null=True)),
                ('usuariocreacion', models.CharField(blank=True, db_column='usuarioCreacion', max_length=20, null=True)),
                ('fechacreacion', models.DateTimeField(blank=True, db_column='fechaCreacion', null=True)),
                ('usuariomodificacion', models.CharField(blank=True, db_column='usuarioModificacion', max_length=20, null=True)),
                ('fechamodificacion', models.DateTimeField(blank=True, db_column='fechaModificacion', null=True)),
                ('estado', models.SmallIntegerField()),
            ],
            options={
                'db_table': 'atencionAmbulatoria',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Citaproceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idcita', models.IntegerField(db_column='idCita')),
                ('idestadocita', models.IntegerField(db_column='idEstadoCita')),
                ('idpaciente', models.IntegerField(db_column='idPaciente')),
                ('idcitatipo', models.IntegerField(db_column='idCitaTipo')),
                ('idconvenio', models.IntegerField(db_column='idConvenio')),
                ('observacion', models.CharField(blank=True, db_column='Observacion', max_length=100, null=True)),
                ('usuariocreacion', models.CharField(db_column='usuarioCreacion', max_length=20)),
                ('fechacreacion', models.DateTimeField(db_column='fechaCreacion')),
            ],
            options={
                'db_table': 'CitaProceso',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Citatipo',
            fields=[
                ('idcitatipo', models.AutoField(db_column='idCitaTipo', primary_key=True, serialize=False)),
                ('orden', models.IntegerField()),
                ('codigo', models.CharField(max_length=10)),
                ('descripcion', models.CharField(max_length=30)),
                ('estado', models.SmallIntegerField()),
            ],
            options={
                'db_table': 'CitaTipo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Citatipoespecialidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nocitas', models.IntegerField(db_column='noCitas')),
            ],
            options={
                'db_table': 'CitaTipoEspecialidad',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Convenio',
            fields=[
                ('idconvenio', models.AutoField(db_column='idConvenio', primary_key=True, serialize=False)),
                ('codigo', models.CharField(blank=True, max_length=10, null=True)),
                ('nombre', models.CharField(blank=True, max_length=50, null=True)),
                ('fechainicio', models.DateField(blank=True, db_column='fechaInicio', null=True)),
                ('fechafin', models.DateField(blank=True, db_column='fechaFin', null=True)),
                ('usuariocreacion', models.CharField(blank=True, db_column='usuarioCreacion', max_length=20, null=True)),
                ('fechacreacion', models.DateField(blank=True, db_column='fechaCreacion', null=True)),
                ('usuariomodificacion', models.CharField(blank=True, db_column='usuarioModificacion', max_length=20, null=True)),
                ('fechamodificacion', models.DateField(blank=True, db_column='fechaModificacion', null=True)),
                ('estado', models.SmallIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'convenio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Convenioespecialidad',
            fields=[
                ('idconvenioespecialidad', models.AutoField(db_column='idConvenioEspecialidad', primary_key=True, serialize=False)),
                ('codigo', models.CharField(blank=True, max_length=20, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=300, null=True)),
                ('fechainicio', models.DateField(blank=True, db_column='fechaInicio', null=True)),
                ('fechafin', models.DateField(blank=True, db_column='fechaFin', null=True)),
                ('usuariocreacion', models.CharField(blank=True, db_column='usuarioCreacion', max_length=20, null=True)),
                ('fechacreacion', models.DateTimeField(blank=True, db_column='fechaCreacion', null=True)),
                ('usuariomodificacion', models.CharField(blank=True, db_column='usuarioModificacion', max_length=20, null=True)),
                ('fechamodificacion', models.DateTimeField(blank=True, db_column='fechaModificacion', null=True)),
                ('estado', models.SmallIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'convenioEspecialidad',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.SmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('iddocumento', models.AutoField(db_column='idDocumento', primary_key=True, serialize=False)),
                ('codigo', models.CharField(blank=True, max_length=20, null=True)),
                ('nombre', models.CharField(blank=True, max_length=50, null=True)),
                ('usuariocreacion', models.CharField(blank=True, db_column='usuarioCreacion', max_length=20, null=True)),
                ('fechacreacion', models.DateTimeField(blank=True, db_column='fechaCreacion', null=True)),
                ('usuariomodificacion', models.CharField(blank=True, db_column='usuarioModificacion', max_length=20, null=True)),
                ('fechamodificacion', models.DateTimeField(blank=True, db_column='fechaModificacion', null=True)),
                ('estado', models.SmallIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'documento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Documentoconvenio',
            fields=[
                ('iddocumentoconvenio', models.AutoField(db_column='idDocumentoConvenio', primary_key=True, serialize=False)),
                ('fechainicio', models.DateField(blank=True, db_column='fechaInicio', null=True)),
                ('fechafin', models.DateField(blank=True, db_column='fechaFin', null=True)),
                ('usuariocreacion', models.CharField(blank=True, db_column='usuarioCreacion', max_length=20, null=True)),
                ('fechacreacion', models.DateTimeField(blank=True, db_column='fechaCreacion', null=True)),
                ('usuariomodificacion', models.CharField(blank=True, db_column='usuarioModificacion', max_length=20, null=True)),
                ('fechamodificacion', models.DateTimeField(blank=True, db_column='fechaModificacion', null=True)),
                ('estado', models.SmallIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'documentoConvenio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Estadocita',
            fields=[
                ('idestadocita', models.AutoField(db_column='idEstadoCita', primary_key=True, serialize=False)),
                ('orden', models.SmallIntegerField(db_column='Orden')),
                ('codigo', models.CharField(blank=True, db_column='Codigo', max_length=50, null=True)),
                ('descripcion', models.CharField(blank=True, db_column='Descripcion', max_length=50, null=True)),
                ('estado', models.IntegerField(db_column='Estado')),
                ('idestadopadre', models.IntegerField(blank=True, db_column='idEstadoPadre', null=True)),
            ],
            options={
                'db_table': 'estadoCita',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('idhorario', models.AutoField(db_column='idHorario', primary_key=True, serialize=False)),
                ('diasemana', models.IntegerField(db_column='diaSemana')),
                ('h1inicio', models.DateTimeField(db_column='h1Inicio')),
                ('h1fin', models.DateTimeField(db_column='h1Fin')),
                ('h2inicio', models.DateTimeField(db_column='h2Inicio')),
                ('h2fin', models.DateTimeField(db_column='h2Fin')),
                ('estado', models.IntegerField()),
                ('tiempo', models.IntegerField(blank=True, null=True)),
                ('usuariocreacion', models.CharField(db_column='usuarioCreacion', max_length=20)),
                ('fechacreacion', models.DateTimeField(db_column='fechaCreacion')),
                ('usuariomodificacion', models.CharField(db_column='usuarioModificacion', max_length=20)),
                ('fechamodificacion', models.DateTimeField(db_column='fechaModificacion')),
            ],
            options={
                'db_table': 'horario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ordenatencion',
            fields=[
                ('idordenatencion', models.AutoField(db_column='idOrdenAtencion', primary_key=True, serialize=False)),
                ('fechainicio', models.DateField(blank=True, db_column='fechaInicio', null=True)),
                ('fechafin', models.DateField(blank=True, db_column='fechaFin', null=True)),
                ('usuariocreacion', models.CharField(blank=True, db_column='usuarioCreacion', max_length=20, null=True)),
                ('fechacreacion', models.DateField(blank=True, db_column='fechaCreacion', null=True)),
                ('usuariomodificacion', models.CharField(blank=True, db_column='usuarioModificacion', max_length=20, null=True)),
                ('fechamodificacion', models.DateField(blank=True, db_column='fechaModificacion', null=True)),
                ('estado', models.SmallIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ordenAtencion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ordenatenciondocumento',
            fields=[
                ('idordenatenciondocumento', models.AutoField(db_column='idOrdenAtencionDocumento', primary_key=True, serialize=False)),
                ('path', models.CharField(blank=True, max_length=2000, null=True)),
                ('fechainicio', models.DateField(blank=True, db_column='fechaInicio', null=True)),
                ('fechafin', models.DateField(blank=True, db_column='fechaFin', null=True)),
                ('usuariocreacion', models.CharField(blank=True, db_column='usuarioCreacion', max_length=20, null=True)),
                ('fechacreacion', models.DateField(blank=True, db_column='fechaCreacion', null=True)),
                ('usuariomodificacion', models.CharField(blank=True, db_column='usuarioModificacion', max_length=20, null=True)),
                ('fechamodificacion', models.DateField(blank=True, db_column='fechaModificacion', null=True)),
                ('estado', models.SmallIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ordenAtencionDocumento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('idpaciente', models.AutoField(db_column='idPaciente', primary_key=True, serialize=False)),
                ('identificacion', models.CharField(blank=True, max_length=18, null=True)),
                ('tipoidentificacion', models.CharField(blank=True, db_column='tipoIdentificacion', max_length=18, null=True)),
                ('nombrepaciente', models.CharField(blank=True, db_column='nombrePaciente', max_length=200, null=True)),
                ('apellidopaterno', models.CharField(blank=True, db_column='apellidoPaterno', max_length=50, null=True)),
                ('apellidomaterno', models.CharField(blank=True, db_column='apellidoMaterno', max_length=50, null=True)),
                ('nombre1', models.CharField(blank=True, max_length=60, null=True)),
                ('nombre2', models.CharField(blank=True, max_length=60, null=True)),
                ('observacion', models.CharField(blank=True, max_length=300, null=True)),
                ('direccion', models.CharField(blank=True, max_length=150, null=True)),
                ('telefonoconvencional', models.CharField(blank=True, db_column='telefonoConvencional', max_length=30, null=True)),
                ('telefonocelular', models.CharField(blank=True, db_column='telefonoCelular', max_length=30, null=True)),
                ('estadoregistro', models.SmallIntegerField(blank=True, db_column='estadoRegistro', null=True)),
                ('ciudad', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('historiaclinica', models.CharField(blank=True, db_column='historiaClinica', max_length=20, null=True)),
                ('fechanacimiento', models.DateField(blank=True, db_column='fechaNacimiento', null=True)),
                ('usuariocreacion', models.CharField(blank=True, db_column='usuarioCreacion', max_length=20, null=True)),
                ('fechacreacion', models.DateTimeField(blank=True, db_column='fechaCreacion', null=True)),
                ('usuariomodificacion', models.CharField(blank=True, db_column='usuarioModificacion', max_length=20, null=True)),
                ('fechamodificacion', models.DateTimeField(blank=True, db_column='fechaModificacion', null=True)),
                ('rutaimagen', models.CharField(blank=True, db_column='rutaImagen', max_length=200, null=True)),
                ('provincia', models.CharField(blank=True, max_length=20, null=True)),
                ('canton', models.CharField(blank=True, max_length=20, null=True)),
                ('parroquia', models.CharField(blank=True, max_length=20, null=True)),
                ('barrio', models.CharField(blank=True, max_length=20, null=True)),
                ('zona', models.CharField(blank=True, max_length=3, null=True)),
                ('lugarnacimiento', models.CharField(blank=True, db_column='lugarNacimiento', max_length=25, null=True)),
                ('nacionalidad', models.CharField(blank=True, max_length=20, null=True)),
                ('grupocultural', models.CharField(blank=True, db_column='grupoCultural', max_length=15, null=True)),
                ('genero', models.CharField(blank=True, max_length=3, null=True)),
                ('estadocivil', models.CharField(blank=True, db_column='estadoCivil', max_length=10, null=True)),
                ('origencontacto', models.CharField(db_column='origenContacto', max_length=50)),
            ],
            options={
                'db_table': 'paciente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pacienteagenda',
            fields=[
                ('idpaciente', models.AutoField(db_column='idPaciente', primary_key=True, serialize=False)),
                ('idusuario', models.IntegerField(blank=True, db_column='idUsuario', null=True)),
                ('nombres', models.CharField(db_column='Nombres', max_length=60)),
                ('apellidos', models.CharField(db_column='Apellidos', max_length=60)),
                ('fechanacimiento', models.DateField(db_column='FechaNacimiento')),
                ('cedula', models.CharField(db_column='Cedula', max_length=13, unique=True)),
                ('genero', models.SmallIntegerField(db_column='Genero')),
                ('correo', models.CharField(blank=True, db_column='Correo', max_length=80, null=True)),
                ('activo', models.BooleanField(db_column='Activo')),
                ('fechacrea', models.DateTimeField(db_column='FechaCrea')),
                ('usuariocrea', models.CharField(db_column='UsuarioCrea', max_length=60)),
                ('fechamodifica', models.DateTimeField(db_column='FechaModifica')),
                ('usuariomodifica', models.CharField(db_column='UsuarioModifica', max_length=60)),
            ],
            options={
                'db_table': 'PacienteAgenda',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pacientecontacto',
            fields=[
                ('idpacientecontacto', models.AutoField(db_column='idPacienteContacto', primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('direccion', models.CharField(blank=True, max_length=100, null=True)),
                ('telefono', models.CharField(blank=True, max_length=13, null=True)),
                ('email', models.CharField(blank=True, max_length=25, null=True)),
                ('parentesco', models.CharField(blank=True, max_length=15, null=True)),
                ('observacion', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'pacienteContacto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pacientedetalle',
            fields=[
                ('idpacientedetalle', models.AutoField(db_column='idPacienteDetalle', primary_key=True, serialize=False)),
                ('discapacidad', models.SmallIntegerField(blank=True, null=True)),
                ('tipodiscapacidad', models.CharField(blank=True, db_column='tipoDiscapacidad', max_length=50, null=True)),
                ('identificaciondiscapacidad', models.CharField(blank=True, db_column='identificacionDiscapacidad', max_length=15, null=True)),
                ('porcentajediscapacidad', models.SmallIntegerField(blank=True, db_column='porcentajeDiscapacidad', null=True)),
                ('otroseguro', models.SmallIntegerField(blank=True, db_column='otroSeguro', null=True)),
                ('descripcionotroseguro', models.CharField(blank=True, db_column='descripcionOtroSeguro', max_length=15, null=True)),
                ('nivelinstruccion', models.CharField(blank=True, db_column='nivelInstruccion', max_length=20, null=True)),
            ],
            options={
                'db_table': 'pacienteDetalle',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pacientediagnostico',
            fields=[
                ('idpacientediagnostico', models.AutoField(db_column='idPacienteDiagnostico', primary_key=True, serialize=False)),
                ('idcie10', models.IntegerField(blank=True, db_column='idCie10', null=True)),
                ('fechainicio', models.DateField(blank=True, db_column='fechaInicio', null=True)),
                ('fechafin', models.DateField(blank=True, db_column='fechaFin', null=True)),
            ],
            options={
                'db_table': 'pacienteDiagnostico',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pacientefacturacion',
            fields=[
                ('idpacientefacturacion', models.AutoField(db_column='idPacienteFacturacion', primary_key=True, serialize=False)),
                ('identificacion', models.CharField(blank=True, max_length=18, null=True)),
                ('tipoidentificacion', models.CharField(blank=True, db_column='tipoIdentificacion', max_length=18, null=True)),
                ('nombre', models.CharField(blank=True, max_length=50, null=True)),
                ('direccion', models.CharField(blank=True, max_length=100, null=True)),
                ('telefono', models.CharField(blank=True, max_length=13, null=True)),
                ('email', models.CharField(blank=True, max_length=25, null=True)),
            ],
            options={
                'db_table': 'pacienteFacturacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PanelAtencion',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('valor_consulta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_medicinas', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'panel_atencion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PanelCita',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('estado', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'panel_cita',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PanelEspecialidad',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=120)),
            ],
            options={
                'db_table': 'panel_especialidad',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PanelServicio',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=120)),
            ],
            options={
                'db_table': 'panel_servicio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Profesional',
            fields=[
                ('idprofesional', models.AutoField(db_column='idProfesional', primary_key=True, serialize=False)),
                ('nombres', models.CharField(blank=True, max_length=50, null=True)),
                ('apellidos', models.CharField(blank=True, max_length=50, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=50, null=True)),
                ('usuariocreacion', models.CharField(blank=True, db_column='usuarioCreacion', max_length=20, null=True)),
                ('fechacreacion', models.DateTimeField(blank=True, db_column='fechaCreacion', null=True)),
                ('usuariomodificacion', models.CharField(blank=True, db_column='usuarioModificacion', max_length=20, null=True)),
                ('fechamodificacion', models.DateTimeField(blank=True, db_column='fechaModificacion', null=True)),
                ('estado', models.SmallIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'profesional',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('idrol', models.AutoField(db_column='idRol', primary_key=True, serialize=False)),
                ('descripcion', models.CharField(db_column='Descripcion', max_length=20)),
                ('orden', models.IntegerField(db_column='Orden')),
                ('activo', models.BooleanField(db_column='Activo')),
            ],
            options={
                'db_table': 'Rol',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sysdiagrams',
            fields=[
                ('name', models.CharField(max_length=128)),
                ('principal_id', models.IntegerField()),
                ('diagram_id', models.AutoField(primary_key=True, serialize=False)),
                ('version', models.IntegerField(blank=True, null=True)),
                ('definition', models.BinaryField(blank=True, max_length='max', null=True)),
            ],
            options={
                'db_table': 'sysdiagrams',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ticketparqueadero',
            fields=[
                ('idticket', models.AutoField(db_column='idTicket', primary_key=True, serialize=False)),
                ('noticket', models.CharField(blank=True, db_column='NoTicket', max_length=10, null=True)),
                ('placa', models.CharField(blank=True, db_column='Placa', max_length=10, null=True)),
                ('horaingreso', models.DateTimeField(blank=True, db_column='HoraIngreso', null=True)),
                ('horasalida', models.DateTimeField(blank=True, db_column='HoraSalida', null=True)),
                ('valor', models.DecimalField(blank=True, db_column='Valor', decimal_places=4, max_digits=19, null=True)),
                ('autorizado', models.DecimalField(blank=True, db_column='Autorizado', decimal_places=4, max_digits=19, null=True)),
                ('observacion', models.CharField(blank=True, db_column='Observacion', max_length=50, null=True)),
                ('fechacreacion', models.DateTimeField(blank=True, db_column='FechaCreacion', null=True)),
                ('fechamodificacion', models.DateTimeField(blank=True, db_column='FechaModificacion', null=True)),
                ('activo', models.BooleanField(blank=True, db_column='Activo', null=True)),
            ],
            options={
                'db_table': 'ticketParqueadero',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Triage',
            fields=[
                ('idtriage', models.AutoField(db_column='idTriage', primary_key=True, serialize=False)),
                ('codigo', models.CharField(blank=True, max_length=20, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=300, null=True)),
                ('usuariocreacion', models.CharField(blank=True, db_column='usuarioCreacion', max_length=20, null=True)),
                ('fechacreacion', models.DateTimeField(blank=True, db_column='fechaCreacion', null=True)),
                ('usuariomodificacion', models.CharField(blank=True, db_column='usuarioModificacion', max_length=20, null=True)),
                ('fechamodificacion', models.DateTimeField(blank=True, db_column='fechaModificacion', null=True)),
                ('estado', models.SmallIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'triage',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('idusuario', models.AutoField(db_column='idUsuario', primary_key=True, serialize=False)),
                ('nombres', models.CharField(blank=True, db_column='Nombres', max_length=60, null=True)),
                ('apellidos', models.CharField(blank=True, db_column='Apellidos', max_length=60, null=True)),
                ('login', models.CharField(db_column='Login', max_length=60)),
                ('contrasenia', models.CharField(db_column='Contrasenia', max_length=60)),
                ('cedula', models.CharField(db_column='Cedula', max_length=13, unique=True)),
                ('correo', models.CharField(db_column='Correo', max_length=80)),
                ('activo', models.BooleanField(db_column='Activo')),
            ],
            options={
                'db_table': 'Usuario',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='cita',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='especialidad',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='servicio',
            options={'managed': False},
        ),
        migrations.DeleteModel(
            name='Atencion',
        ),
    ]
