# Generated by Django 5.2 on 2025-12-23 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0002_apoyodiagnostico_atencionambulatoria_authgroup_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='panelatencion',
            options={'managed': True, 'verbose_name': 'Atención (panel)'},
        ),
        migrations.AlterModelOptions(
            name='panelespecialidad',
            options={'managed': True, 'verbose_name': 'Especialidad (panel)'},
        ),
        migrations.AlterModelOptions(
            name='panelservicio',
            options={'managed': True, 'verbose_name': 'Servicio (panel)'},
        ),
        migrations.AlterModelTable(
            name='cita',
            table='Cita',
        ),
        migrations.AlterModelTable(
            name='especialidad',
            table='especialidad',
        ),
        migrations.AlterModelTable(
            name='servicio',
            table='servicio',
        ),
    ]
