# Generated by Django 5.2 on 2025-12-23 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0004_add_accessquery'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accessquery',
            options={'verbose_name': 'Consulta Access', 'verbose_name_plural': 'Consultas Access'},
        ),

        # NOTE: The `panel_atencion` table is created in 0006_create_panelatencion_table
        # with many of the columns below; avoid adding them again here to prevent
        # duplicate column errors when building test databases.

        migrations.AlterField(
            model_name='accessquery',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='panelatencion',
            name='valor_consulta',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='panelatencion',
            name='valor_medicinas',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        # Unique constraint on (source_table, source_hash) is created in 0006_create_panelatencion_table
        # and does not need to be added again here.

        migrations.AlterModelTable(
            name='ordenatencion',
            table=None,
        ),
    ]
