# Generated by Django 5.2 on 2025-12-23 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0005_alter_accessquery_options_panelatencion_edad_and_more'),
        ('panel', '0006_create_panelatencion_table'),
    ]

    operations = [
    ]
