# Generated by Django 5.2 on 2025-12-24 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0008_create_dailyeqctacli_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='panelatencion',
            name='edad',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='panelatencion',
            name='especialidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='panel.panelespecialidad'),
        ),
        migrations.AddField(
            model_name='panelatencion',
            name='genero',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='panelatencion',
            name='institucion',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='panelatencion',
            name='raw',
            field=models.JSONField(blank=True, help_text='Contenido crudo de la fila importada', null=True),
        ),
        migrations.AddField(
            model_name='panelatencion',
            name='servicio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='panel.panelservicio'),
        ),
        migrations.AddField(
            model_name='panelatencion',
            name='solicitado_a',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='panelatencion',
            name='source_hash',
            field=models.CharField(blank=True, db_index=True, help_text='Hash único de la fila origen para evitar duplicados', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='panelatencion',
            name='source_table',
            field=models.CharField(blank=True, help_text='Tabla origen en Access', max_length=100, null=True),
        ),
        migrations.AddConstraint(
            model_name='panelatencion',
            constraint=models.UniqueConstraint(condition=models.Q(models.Q(('source_table', None), _negated=True), models.Q(('source_hash', None), _negated=True)), fields=('source_table', 'source_hash'), name='uniq_source_row'),
        ),
    ]
